a:18:{s:4:"name";s:8:"Betapace";s:11:"small_descr";s:93:"Betapace is used for treating certain types of irregular heartbeat (ventricular arrhythmias).";s:14:"small_descr_de";s:118:"Betapace wird zur Behandlung von einigen Arten von unregelmäßigem Herzschlag (ventrikuläre Arrhythmien) verwendet. ";s:14:"small_descr_fr";s:125:"Betapace est utilisé pour traiter les certains types du rythme cardiaque irrégulier (les troubles du rythme ventriculaire).";s:14:"small_descr_es";s:119:"Betapace es utilizado para el tratamiento de ciertos tipos de latidos cardíacos irregulares (arritmias ventriculares).";s:14:"small_descr_it";s:112:"Betapace si usa per il trattamento di alcuni tipi del battito del cuore irregolare (extrasistolia ventricolare).";s:10:"full_descr";s:7448:"<p><strong>INDICATIONS </strong></p><p>Betapace is used for treating certain types of irregular heartbeat (ventricular arrhythmias). Betapace is a beta-blocker. It works by helping the heart beat regularly for a longer period of time.</p><p><strong>INSTRUCTIONS&nbsp;</strong></p><p>Use Betapace as directed by your doctor.</p><ul><li>Take Betapace by mouth with or without food. Try      to take it the same way (either with food or without food) each time you      take your dose. Check with your doctor or pharmacist if you have questions      about taking Betapace with food.</li><li>Do not take an antacid that has aluminum or      magnesium in it within 2 hours before or after you take Betapace.</li><li>Taking Betapace at the same time each day will      help you remember to take it.</li><li>Continue to use Betapace even if you feel well.      Do not miss any dose.</li><li>If you miss a dose of Betapace, skip the missed      dose. Do not take 2 doses at once.</li></ul><p>Ask your health care provider any questions you may have about how to use Betapace.</p><p><strong>STORAGE</strong></p><p>Store Betapace at room temperature, between 68 and 77 degrees F (20 and 25 degrees C). Store away from heat, moisture, and light. Do not store in the bathroom. Keep Betapace out of the reach of children and away from pets.</p><p><strong>MORE INFO:</strong></p><p><strong>Active Ingredient: </strong>Sotalol HCl.</p><p><strong>SAFETY INFORMATION</strong></p><p><strong>Do NOT use Betapace if:</strong></p>
<ul>
<li>you are allergic to any ingredient in      Betapace</li>
<li>you have certain heart problems (eg,      severe low heart rate, uncontrolled heart failure, certain types of      abnormal heartbeat rhythm), low blood potassium or magnesium levels,      severe kidney problems, or a history of asthma</li>
<li>you are taking cisapride, astemizole,      terfenadine, mibefradil, dofetilide, or a theophylline (eg, aminophylline).</li>
</ul>
<p>Contact your doctor or health care provider right away if any of these apply to you.</p>
<p>Some medical conditions may interact with Betapace. Tell your doctor or pharmacist if you have any medical conditions, especially if any of the following apply to you:</p>
<ul>
<li>if you are pregnant, planning to become pregnant,      or are breast-feeding</li>
<li>if you are taking any prescription or      nonprescription medicine, herbal preparation, or dietary supplement</li>
<li>if you have allergies to medicines, foods,      or other substances</li>
<li>if you have breathing or lung problems      (eg, chronic obstructive pulmonary disorder [COPD], asthma), a decreased      appetite, an overactive thyroid, kidney problems, bronchitis, diabetes,      blood flow problems, a tumor on your adrenal gland, or other heart      problems</li>
<li>if you are scheduled for surgery.</li>
</ul>
<p>Some medicines may interact with Betapace. Tell your health care provider if you are taking any other medicines, especially any of the following:</p>
<ul>
<li>Indomethacin or phenylpropanolamine      because they may decrease Betapace's effectiveness</li>
<li>Clonidine, diltiazem, mibefradil, nifedipine,      or verapamil because the risk of side effects, such as low blood pressure      or heart problems, may be increased</li>
<li>Amiodarone, antiarrhythmics (eg,      quinidine, propafenone), arsenic, cisapride , dofetilide, droperidol, H<sub>1</sub> antagonists (eg, astemizole, terfenadine), ketanserin, macrolides and      ketolides (eg, erythromycin, azithromycin), mefloquine, phosphodiesterase      type 5 inhibitors (eg, sildenafil), phenothiazines (eg, thioridazine),      quinolones (eg, ciprofloxacin), or ziprasidone because the risk of abnormal      heart rhythms may be increased</li>
<li>Bupivacaine, cocaine, epinephrine,      insulin, lidocaine, meglitinide antidiabetics (eg, nateglinide),      nifedipine, or quinazolines (eg, prazosin) because the risk of their side      effects may be increased by Betapace</li>
<li>Certain stimulants (eg, albuterol,      pseudoephedrine), phenformin, or theophyllines (eg, aminophylline) because      their effectiveness may be decreased by Betapace.</li>
</ul>
<p>This may not be a complete list of all interactions that may occur. Ask your health care provider if Betapace may interact with other medicines that you take. Check with your health care provider before you start, stop, or change the dose of any medicine.</p>
<p><strong>Important safety information:</strong></p>
<ul>
<li>Betapace may cause drowsiness, dizziness,      or lightheadedness. These effects may be worse if you take it with alcohol      or certain medicines. Use Betapace with caution. Do not drive or perform      other possibly unsafe tasks until you know how you react to it.</li>
<li>Betapace may cause dizziness,      lightheadedness, or fainting; alcohol, hot weather, exercise, or fever may      increase these effects. To prevent them, sit up or stand slowly,      especially in the morning. Sit or lie down at the first sign of any of      these effects.</li>
<li>Tell your doctor or dentist that you take      Betapace before you receive any medical or dental care, emergency care, or      surgery.</li>
<li>Do not suddenly stop taking Betapace.      Sharp chest pain, irregular heartbeat, and sometimes heart attack may      occur if you suddenly stop Betapace. The risk may be greater if you have      certain types of heart disease. Heart disease is common and you may not      know you have it. Your doctor should slowly lower your dose over several      weeks if you need to stop taking it. Limit physical activity while you are      lowering your dose. If new or worsened chest pain or other heart problems      occur, contact your doctor right away. You may need to start taking      Betapace again.</li>
<li>Lab tests, including heart function,      kidney function, and blood pressure monitoring, may be performed while you      use Betapace. These tests may be used to monitor your condition or check      for side effects. Be sure to keep all doctor and lab appointments.</li>
<li>Pregnancy and breast-feeding: If you      become pregnant, contact your doctor. You will need to discuss the      benefits and risks of using Betapace while you are pregnant. Betapace is      found in breast milk. Do not breastfeed while taking Betapace.</li>
</ul><p><strong>SIDE EFFECTS</strong></p><p>All medicines may cause side effects, but many people have no, or minor, side effects.</p>
<p>Check with your doctor if any of these most common side effects persist or become bothersome:</p>
<p>Dizziness; drowsiness; headache; light-headedness; tiredness; trouble sleeping.</p>
<p>Seek medical attention right away if any of these severe side effects occur:</p>
<p>Severe allergic reactions (rash; hives; itching; difficulty breathing; tightness in the chest; swelling of the mouth, face, lips, or tongue); abnormally fast, slow, or irregular heartbeat; changes in vision; decreased appetite; excessive thirst; numbness of an arm or leg; severe or persistent nausea, vomiting, or diarrhea; severe stomach pain; sharp or crushing chest pain; sudden leg pain; sudden severe headache, vomiting, dizziness, or fainting; sudden shortness of breath; unusual sweating.</p>
<p>This is not a complete list of all side effects that may occur. If you have questions about side effects, contact your health care provider.</p>";s:13:"full_descr_de";s:0:"";s:13:"full_descr_fr";s:0:"";s:13:"full_descr_es";s:0:"";s:13:"full_descr_it";s:0:"";s:9:"min_price";s:8:"0.732488";s:9:"pack_name";s:5:"pills";s:4:"type";s:2:"mg";s:7:"analogs";N;s:8:"synonims";a:29:{i:0;s:7:"Talozin";i:1;s:7:"Sotoger";i:2;s:8:"Sotastad";i:3;s:7:"Sotapor";i:4;s:8:"Sotanorm";i:5;s:9:"Sotamerck";i:6;s:7:"Sotamed";i:7;s:9:"Sotalolum";i:8;s:8:"Sotalolo";i:9;s:7:"Sotalin";i:10;s:7:"Sotalex";i:11;s:9:"Sotahexal";i:12;s:9:"Sotagamma";i:13;s:7:"Sotacor";i:14;s:8:"Sotabeta";i:15;s:9:"Sota-saar";i:16;s:10:"Sota-puren";i:17;s:6:"Sorine";i:18;s:8:"Solavert";i:19;s:9:"Rytmobeta";i:20;s:9:"Rentibloc";i:21;s:11:"Pms-sotalol";i:22;s:7:"Jutalex";i:23;s:7:"Hipecor";i:24;s:10:"Darob mite";i:25;s:5:"Darob";i:26;s:6:"Cardol";i:27;s:12:"Beta-cardone";i:28;s:8:"Biosotal";}s:18:"active_ingredients";N;s:8:"packings";a:1:{i:40;a:7:{i:4173;a:5:{s:10:"id_packing";s:4:"4173";s:5:"count";s:2:"30";s:6:"dosage";d:40;s:14:"price_per_pill";s:6:"1.2008";s:4:"name";s:8:"Betapace";}i:4174;a:5:{s:10:"id_packing";s:4:"4174";s:5:"count";s:2:"60";s:6:"dosage";d:40;s:14:"price_per_pill";s:7:"0.94536";s:4:"name";s:8:"Betapace";}i:4175;a:5:{s:10:"id_packing";s:4:"4175";s:5:"count";s:2:"90";s:6:"dosage";d:40;s:14:"price_per_pill";s:7:"0.86021";s:4:"name";s:8:"Betapace";}i:4176;a:5:{s:10:"id_packing";s:4:"4176";s:5:"count";s:3:"120";s:6:"dosage";d:40;s:14:"price_per_pill";s:7:"0.81764";s:4:"name";s:8:"Betapace";}i:4177;a:5:{s:10:"id_packing";s:4:"4177";s:5:"count";s:3:"180";s:6:"dosage";d:40;s:14:"price_per_pill";s:7:"0.77506";s:4:"name";s:8:"Betapace";}i:4178;a:5:{s:10:"id_packing";s:4:"4178";s:5:"count";s:3:"270";s:6:"dosage";d:40;s:14:"price_per_pill";s:7:"0.74668";s:4:"name";s:8:"Betapace";}i:4179;a:5:{s:10:"id_packing";s:4:"4179";s:5:"count";s:3:"360";s:6:"dosage";d:40;s:14:"price_per_pill";s:7:"0.73249";s:4:"name";s:8:"Betapace";}}}}