a:18:{s:4:"name";s:5:"Luvox";s:11:"small_descr";s:120:"Luvox is indicated for the treatment of obsessions and compulsions in patients with obsessive compulsive disorder (OCD).";s:14:"small_descr_de";s:149:"Luvox wird zur Behandlung von Obsessionen und Zwangen bei Patienten mit Zwangsstörung (engl. "Obsessive Compulsive Disorder" bzw. "OCD") angewendet.";s:14:"small_descr_fr";s:139:"Luvox est indiqué pour le traitement des obsessions et des compulsions aux patients qui souffrent du trouble obsessionnel compulsif (TOC).";s:14:"small_descr_es";s:124:"Luvox es indicado para el tratamiento de las obsesiones y compulsiones en pacientes con trastorno obsesivo-compulsivo (TOC).";s:14:"small_descr_it";s:123:"Luvox è indicato per il trattamento delle ossessioni e costrizioni in pazienti con il disturbo ossessivo-compulsivo (DOC).";s:10:"full_descr";s:10781:"<p><strong>INDICATIONS </strong></p><p>Luvox is indicated for the treatment of obsessions and compulsions in patients with obsessive compulsive disorder (OCD). Luvox is a selective serotonin reuptake inhibitor (SSRI). It works by restoring the balance of serotonin, a natural substance in the brain, which helps to decrease anxiety and obsessive or compulsive behavior.</p><p><strong>INSTRUCTIONS&nbsp;</strong></p><p>Use Luvox as directed by your doctor.</p><ul><li>Take Luvox by mouth with or without food.</li><li>Take Luvox at bedtime unless your doctor tells      you otherwise.</li><li>Continue to take Luvox if you feel well. Do not      miss any dose.</li><li>Do not suddenly stop taking Luvox without      checking with your doctor. Side effects may occur. They may include mental      or mood changes, numbness or tingling of the skin, dizziness, confusion,      headache, trouble sleeping, or unusual tiredness. You will be closely      monitored when you start Luvox and whenever a change in dose is made.</li><li>If you miss a dose of Luvox, take it as soon as      possible. If it is almost time for your next dose, skip the missed dose      and go back to your regular dosing schedule. Do not take 2 doses at once.</li></ul><p>Ask your health care provider any questions you may have about how to use Luvox.</p><p><strong>STORAGE</strong></p><p>Store Luvox at 77 degrees F (25 degrees C). Brief storage at temperatures between 59 and 86 degrees F (15 and 30 degrees C) is permitted. Avoid temperatures above 86 degrees F (30 degrees C). Store away from heat, moisture, and light. Do not store in the bathroom. Keep Luvox out of the reach of children and away from pets.</p><p><strong>MORE INFO:</strong></p><p><strong>Active Ingredient: </strong>Fluvoxamine maleate.</p><p><strong>SAFETY INFORMATION</strong></p><p><strong>Do NOT use Luvox if:</strong></p>
<ul>
<li>you are allergic to any ingredient in Luvox </li>
<li>you are taking or have taken a monoamine      oxidase inhibitor (MAOI) (eg, phenelzine) or St. John's wort within the      last 14 days</li>
<li>you are taking alosetron, astemizole, a      fenfluramine derivative (eg, dexfenfluramine), nefazodone, pimozide,      ramelteon, sibutramine, terfenadine, thioridazine, or tizanidine.</li>
</ul>
<p>Contact your doctor or health care provider right away if any of these apply to you.</p>
<p>Some medical conditions may interact with Luvox. Tell your doctor or pharmacist if you have any medical conditions, especially if any of the following apply to you:</p>
<ul>
<li>if you are pregnant, planning to become      pregnant, or are breast-feeding</li>
<li>if you are taking any prescription or      nonprescription medicine, herbal preparation, or dietary supplement</li>
<li>if you have allergies to medicines, foods,      or other substances</li>
<li>if you or a family member has a history of      bipolar disorder (manic-depression), other mental or mood problems,      suicidal thoughts or attempts, or alcohol or substance abuse</li>
<li>if you have a history of seizures, heart      problems, liver problems, stomach or bowel bleeding, diabetes, blood or      bone marrow problems, or metabolism problems</li>
<li>if you are dehydrated, have low blood      sodium levels, or drink alcohol or smoke</li>
<li>if you will be having electroconvulsive      therapy (ECT).</li>
</ul>
<p>Some medicines may interact with Luvox. Tell your health care provider if you are taking any other medicines, especially any of the following:</p>
<ul>
<li>Anorexiants (eg, phentermine),      fenfluramine derivatives (eg, dexfenfluramine), linezolid, lithium, MAOIs      (eg, phenelzine), medicines for mental problems (eg, quetiapine),      metoclopramide, nefazodone, quinidine, rasagiline, selegiline, serotonin      5-HT<sub>1</sub> receptor agonists (eg, sumatriptan), sibutramine, St.      John's wort, trazodone, or tryptophan because severe side effects, such as      a reaction that may include fever, rigid muscles, blood pressure changes,      mental changes, confusion, irritability, agitation, delirium, and coma,      may occur</li>
<li>Anticoagulants (eg, warfarin), aspirin, or      nonsteroidal anti-inflammatory drugs (NSAIDs) (eg, ibuprofen) because the      risk of bleeding, including stomach bleeding, may be increased</li>
<li>Diuretics (eg, furosemide,      hydrochlorothiazide) because the risk of low blood sodium levels may be      increased</li>
<li>Tramadol because the risk of seizures may      be increased</li>
<li>Astemizole, cisapride, phenothiazines (eg,      chlorpromazine, thioridazine), pimozide, or terfenadine because severe      heart problems, including irregular heartbeat, may occur</li>
<li>Cyproheptadine because it may decrease      Luvox's effectiveness</li>
<li>Alosetron, aripiprazole, benzodiazepines      (eg, alprazolam, diazepam), beta-blockers (eg, metoprolol, propranolol),      carbamazepine, clozapine, diltiazem, methadone, mexiletine, phenytoin,      ramelteon, risperidone, serotonin-norepinephrine reuptake inhibitors      (SNRIs) (eg, venlafaxine), tacrine, theophylline, tizanidine , or      tricyclic antidepressants (eg, amitriptyline) because the risk of their      side effects may be increased by Luvox.</li>
</ul>
<p>This may not be a complete list of all interactions that may occur. Ask your health care provider if Luvox may interact with other medicines that you take. Check with your health care provider before you start, stop, or change the dose of any medicine.</p>
<p><strong>Important safety information:</strong></p>
<ul>
<li>Luvox may cause drowsiness or dizziness.      These effects may be worse if you take it with alcohol or certain      medicines. Use Luvox with caution. Do not drive or perform other possible      unsafe tasks until you know how you react to it.</li>
<li>Do not drink alcohol while you are using      Luvox.</li>
<li>Check with your doctor before you use      medicines that may cause drowsiness (eg, sleep aids, muscle relaxers)      while you are using Luvox; it may add to their effects. Ask your      pharmacist if you have questions about which medicines may cause      drowsiness.</li>
<li>Several weeks may pass before your      symptoms improve. Do NOT take more than the recommended dose, change your      dose, or use Luvox for longer than prescribed without checking with your      doctor.</li>
<li>Children, teenagers, and young adults who      take Luvox may be at increased risk for suicidal thoughts or actions.      Watch patients who take Luvox closely. Contact the doctor at once if new,      worsened, or sudden symptoms such as depressed mood; anxious, restless, or      irritable behavior; panic attacks; or any unusual change in mood or      behavior occur. Contact the doctor right away if any signs of suicidal thoughts      or actions occur.</li>
<li>If your doctor tells you to stop taking      Luvox, you will need to wait for several weeks before beginning to take      certain other medicines (eg, MAOIs, nefazodone). Ask your doctor when you      should start to take your new medicines after you have stopped taking      Luvox.</li>
<li>Serotonin syndrome is a possibly fatal      syndrome that can be caused by Luvox. Your risk may be greater if you take      Luvox with certain other medicines (eg, MAOIs, "triptans").      Symptoms may include agitation; confusion; hallucinations; coma; fever;      fast or irregular heartbeat; tremor; excessive sweating; and nausea,      vomiting, or diarrhea. Contact your doctor at once if you have any of      these symptoms.</li>
<li>Neuroleptic malignant syndrome (NMS) is a      possibly fatal syndrome that can rarely be caused by Luvox. Symptoms may      include fever; stiff muscles; confusion; abnormal thinking; fast or      irregular heartbeat; and sweating. Contact your doctor at once if you have      any of these symptoms.</li>
<li>Luvox may rarely cause a prolonged,      painful erection. This could happen even when you are not having sex. If      this is not treated right away, it could lead to permanent sexual problems      such as impotence. Contact your doctor right away if this happens.</li>
<li>Caution is advised when using Luvox in the      elderly; they may be more sensitive to its effects, especially low blood      sodium levels.</li>
<li>Luvox should be used with extreme caution      in children; safety and effectiveness in children have not been confirmed.      They may be more sensitive to its effects, especially increased risk of      suicidal thoughts or actions.</li>
<li>Luvox may cause weight changes. Children and      teenagers may need regular weight and growth checks while they take Luvox.</li>
<li>Pregnancy and breast-feeding: Luvox may      cause harm to the fetus if it is used during the last 3 months of      pregnancy. If you become pregnant, contact your doctor. You will need to      discuss the benefits and risks of using Luvox while you are pregnant.      Luvox is found in breast milk. Do not breastfeed while taking Luvox.</li>
</ul><p><strong>SIDE EFFECTS</strong></p><p>All medicines may cause side effects, but many people have no, or minor, side effects.</p>
<p>Check with your doctor if any of these most common side effects persist or become bothersome:</p>
<p>Constipation; decreased sexual ability; diarrhea; dizziness; drowsiness; dry mouth; gas; headache; increased sweating; loss of appetite; nausea; nervousness; sore throat; stomach upset; trouble sleeping; vomiting; weakness.</p>
<p>Seek medical attention right away if any of these severe side effects occur:</p>
<p>Severe allergic reactions (rash; hives; itching; difficulty breathing; tightness in the chest; swelling of the mouth, face, lips, or tongue); bizarre behavior; black or bloody stools; chest pain; confusion; decreased concentration; decreased coordination; exaggerated reflexes; fainting; fast or irregular heartbeat; fever; hallucinations; memory loss; new or worsening agitation, anxiety, depression, panic attacks, aggressiveness, impulsiveness, irritability, hostility, exaggerated feeling of well-being, restlessness, or inability to sit still; painful menstrual periods; persistent, painful erection; red, swollen, blistered, or peeling skin; seizures; severe or persistent headache or trouble sleeping; stiff muscles; stomach pain; suicidal thoughts or attempts; tremor; unusual bruising or bleeding; unusual or severe mental or mood changes; unusual swelling; unusual weakness; vision changes.</p>
<p>This is not a complete list of all side effects that may occur. If you have questions about side effects, contact your health care provider.</p>
<p><strong><em><span style="text-decoration: underline;"><br /></span></em></strong></p>";s:13:"full_descr_de";s:0:"";s:13:"full_descr_fr";s:0:"";s:13:"full_descr_es";s:0:"";s:13:"full_descr_it";s:0:"";s:9:"min_price";s:7:"1.01332";s:9:"pack_name";s:5:"pills";s:4:"type";s:2:"mg";s:7:"analogs";N;s:8:"synonims";a:1:{i:0;s:8:"Luvox cr";}s:18:"active_ingredients";N;s:8:"packings";a:2:{i:100;a:6:{i:4083;a:5:{s:10:"id_packing";s:4:"4083";s:5:"count";s:2:"30";s:6:"dosage";d:100;s:14:"price_per_pill";s:6:"3.1464";s:4:"name";s:5:"Luvox";}i:4084;a:5:{s:10:"id_packing";s:4:"4084";s:5:"count";s:2:"60";s:6:"dosage";d:100;s:14:"price_per_pill";s:7:"2.27917";s:4:"name";s:5:"Luvox";}i:4085;a:5:{s:10:"id_packing";s:4:"4085";s:5:"count";s:2:"90";s:6:"dosage";d:100;s:14:"price_per_pill";s:6:"1.9901";s:4:"name";s:5:"Luvox";}i:4086;a:5:{s:10:"id_packing";s:4:"4086";s:5:"count";s:3:"120";s:6:"dosage";d:100;s:14:"price_per_pill";s:7:"1.84556";s:4:"name";s:5:"Luvox";}i:4087;a:5:{s:10:"id_packing";s:4:"4087";s:5:"count";s:3:"180";s:6:"dosage";d:100;s:14:"price_per_pill";s:7:"1.70102";s:4:"name";s:5:"Luvox";}i:4088;a:5:{s:10:"id_packing";s:4:"4088";s:5:"count";s:3:"270";s:6:"dosage";d:100;s:14:"price_per_pill";s:7:"1.60466";s:4:"name";s:5:"Luvox";}}i:50;a:7:{i:4089;a:5:{s:10:"id_packing";s:4:"4089";s:5:"count";s:2:"30";s:6:"dosage";d:50;s:14:"price_per_pill";s:6:"1.8095";s:4:"name";s:5:"Luvox";}i:4090;a:5:{s:10:"id_packing";s:4:"4090";s:5:"count";s:2:"60";s:6:"dosage";d:50;s:14:"price_per_pill";s:7:"1.37522";s:4:"name";s:5:"Luvox";}i:4091;a:5:{s:10:"id_packing";s:4:"4091";s:5:"count";s:2:"90";s:6:"dosage";d:50;s:14:"price_per_pill";s:7:"1.23046";s:4:"name";s:5:"Luvox";}i:4092;a:5:{s:10:"id_packing";s:4:"4092";s:5:"count";s:3:"120";s:6:"dosage";d:50;s:14:"price_per_pill";s:7:"1.15808";s:4:"name";s:5:"Luvox";}i:4093;a:5:{s:10:"id_packing";s:4:"4093";s:5:"count";s:3:"180";s:6:"dosage";d:50;s:14:"price_per_pill";s:6:"1.0857";s:4:"name";s:5:"Luvox";}i:4094;a:5:{s:10:"id_packing";s:4:"4094";s:5:"count";s:3:"270";s:6:"dosage";d:50;s:14:"price_per_pill";s:7:"1.03745";s:4:"name";s:5:"Luvox";}i:4095;a:5:{s:10:"id_packing";s:4:"4095";s:5:"count";s:3:"360";s:6:"dosage";d:50;s:14:"price_per_pill";s:7:"1.01332";s:4:"name";s:5:"Luvox";}}}}