a:18:{s:4:"name";s:7:"Lanoxin";s:11:"small_descr";s:148:"Lanoxin is used for treating heart failure and slowing the heart rate in patients with chronic atrial fibrillation, a type of abnormal heart rhythm.";s:14:"small_descr_de";s:152:"Lanoxin dient der Behandlung von Herzinsuffizienz und zur Verlangsamung des Herzens bei Patienten mit Vorhofflimmern, ein Typ von Herzrhythmusstörung. ";s:14:"small_descr_fr";s:196:"Lanoxin est utilisé pour traiter l'insuffisance cardiaque et pour ralentir la fréquence cardiaque aux patients qui ont la fibrillation auriculaire chronique, un type de rythme cardiaque anormal.";s:14:"small_descr_es";s:177:"Lanoxin es utilizado para tratar la insuficiencia cardíaca y ralentizar el ritmo cardíaco en pacientes con fibrilación auricular crónica, un tipo de ritmo cardíaco anormal.";s:14:"small_descr_it";s:174:"Lanoxin si usa per il trattamento dell'arresto cordiaco e rallentamento del tasso cardiaco in pazienti con fibrillazione atriale cronica, un tipo del ritmo cardiaco anormale.";s:10:"full_descr";s:7212:"<p><strong>INDICATIONS </strong></p><p>Lanoxin is used for treating heart failure and slowing the heart rate in patients with chronic atrial fibrillation, a type of abnormal heart rhythm. Lanoxin is a digitalis glycoside. It works by increasing the force of contraction of the heart and slowing heart rate.</p><p><strong>INSTRUCTIONS&nbsp;</strong></p><p>Use Lanoxin as directed by your doctor.</p><ul><li>Do not take it in larger amounts or for longer      than recommended. Follow the directions on your prescription label.</li><li>Take Lanoxin with a full glass of water. </li><li>Try to take the medication at the same time every      day.</li><li>To be sure Lanoxin is not causing harmful      effects, your blood may need to be tested on a regular basis. Your kidney      function may also need to be tested. Do not miss any scheduled      appointments.</li><li>Keep taking Lanoxin as directed, even if you feel      well. Get your prescription refilled before you run out of medicine      completely.</li><li>Do not stop taking Lanoxin without first      talking to your doctor. Stopping suddenly may make your condition      worse.&nbsp; </li><li>&nbsp;If you miss a dose of Lanoxin, take it as soon as possible. If      it is almost time for your next dose, skip the missed dose and go back to      your regular dosing schedule. Do not take 2 doses at once.</li></ul><p>Ask your health care provider any questions you may have about how to use Lanoxin.</p><p><strong>STORAGE</strong></p><p>Store Lanoxin at 77 degrees F (25 degrees C). Brief storage at temperatures between 59 and 86 degrees F (15 and 30 degrees C) is permitted. Store away from heat, moisture, and light. Do not store in the bathroom. Keep Lanoxin out of the reach of children and away from pets.</p><p><strong>MORE INFO:</strong></p><p><strong>Active Ingredient:</strong> Digoxin.</p><p><strong>SAFETY INFORMATION</strong></p><p><strong>Do NOT use Lanoxin if:</strong></p>
<ul>
<li>you are allergic to any ingredient in      Lanoxin or other digitalis medicines</li>
<li>you have beriberi heart      disease</li>
<li>you have certain types of heart rhythm      problems, such as ventricular fibrillation.</li>
</ul>
<p>Contact your doctor or health care provider right away if any of these apply to you.</p>
<p>Some medical conditions may interact with Lanoxin. Tell your doctor or pharmacist if you have any medical conditions, especially if any of the following apply to you:</p>
<ul>
<li>if you are pregnant, planning to become      pregnant, or are breast-feeding</li>
<li>if you are taking any prescription or      nonprescription medicine, herbal preparation, or dietary supplement</li>
<li>if you have allergies to medicines, foods,      or other substances</li>
<li>if you have severe heart failure,      inflammation of the heart, coronary artery disease, heart attack, heart      block, extra heart beats (PVCs), certain abnormal heart rhythms, or      fainting due to a heart problem</li>
<li>if you have severe kidney, liver, or lung      problems, or a thyroid problem</li>
<li>if you have low blood levels of calcium,      magnesium, or potassium, or high blood levels of potassium or calcium.</li>
</ul>
<p>Some medicines may interact with Lanoxin. Tell your health care provider if you are taking any other medicines, especially any of the following:</p>
<ul>
<li>Amiodarone, amphotericin B,      anticholinergics (eg, propantheline), beta-blockers (eg, propranolol),      bupivacaine, calcium, certain stimulants (eg, albuterol, amphetamine,      pseudoephedrine), cyclosporine, diltiazem, diphenoxylate, diuretics (eg,      hydrochlorothiazide, furosemide), indomethacin, itraconazole, macrolides      (eg, erythromycin), propafenone, quinidine, quinine, spironolactone,      succinylcholine, tetracyclines (eg, doxycycline), thioamines (eg,      methimazole), or verapamil because they may increase the risk of Lanoxin's      side effects, especially on the heart</li>
<li>Acarbose, certain anticancer medicines,      cholestyramine, colestipol, kaolin-pectin, metoclopramide, penicillamine,      rifampin, sulfasalazine, or thyroid hormones (eg, levothyroxine) because      they may decrease Lanoxin's effectiveness</li>
<li>Oral aminoglycosides (eg, neomycin)      because the actions and side effects of Lanoxin may be increased or      decreased</li>
<li>Spironolactone because it may interfere      with certain lab tests for digoxin blood levels and give false readings.</li>
</ul>
<p>This may not be a complete list of all interactions that may occur. Ask your health care provider if Lanoxin may interact with other medicines that you take. Check with your health care provider before you start, stop, or change the dose of any medicine.</p>
<p><strong>Important safety information:</strong></p>
<ul>
<li>Lanoxin may cause dizziness or blurred      vision. These effects may be worse if you take it with alcohol or certain      medicines. Use Lanoxin with caution. Do not drive or perform other      possible unsafe tasks until you know how you react to it.</li>
<li>Tell your doctor or dentist that you take      Lanoxin before you receive any medical or dental care, emergency care, or      surgery.</li>
<li>Lab tests, including electrocardiogram      (ECG), electrolytes, and blood digoxin levels, may be performed while you      use Lanoxin. These tests may be used to monitor your condition or check      for side effects. Be sure to keep all doctor and lab appointments.</li>
<li>Use Lanoxin with caution in the elderly;      they may be more sensitive to its effects.</li>
<li>Use Lanoxin with extreme caution in infants      who are premature or immature; they may be more sensitive to its effects.</li>
<li>Poisoning may occur in children who      accidently swallow Lanoxin or receive too much medicine. In case of an      overdose, call a doctor or poison control center right away.</li>
<li>Pregnancy and breast-feeding: If you become      pregnant, contact your doctor. You will need to discuss the benefits and      risks of using Lanoxin while you are pregnant. Lanoxin is found in breast      milk. If you are or will be breast-feeding while you use Lanoxin, check      with your doctor. Discuss any possible risks to your baby.</li>
</ul><p><strong>SIDE EFFECTS</strong></p><p>All medicines may cause side effects, but many people have no, or minor, side effects.</p>
<p>Check with your doctor if any of these most common side effects persist or become bothersome:</p>
<p>Diarrhea; nausea.</p>
<p>Seek medical attention right away if any of these severe side effects occur:</p>
<p>Severe allergic reactions (rash; hives; itching; difficulty breathing; tightness in the chest; swelling of the mouth, face, lips, or tongue); blurred vision, yellow vision, or other vision changes; confusion; fast, slow, or irregular heartbeat; hallucinations; mood or mental changes (eg, depression); severe or persistent nausea, vomiting, or stomach pain; unusual bruising or bleeding; unusual tiredness or weakness.</p>
<p>This is not a complete list of all side effects that may occur. If you have questions about side effects, contact your health care provider.</p>";s:13:"full_descr_de";s:0:"";s:13:"full_descr_fr";s:0:"";s:13:"full_descr_es";s:0:"";s:13:"full_descr_it";s:0:"";s:9:"min_price";s:8:"0.396396";s:9:"pack_name";s:5:"pills";s:4:"type";s:2:"mg";s:7:"analogs";a:1:{s:7:"Digoxin";s:14:"Blood Pressure";}s:8:"synonims";a:29:{i:0;s:7:"Vidaxil";i:1;s:8:"Sigmaxin";i:2;s:8:"Purgoxin";i:3;s:11:"Pms-digoxin";i:4;s:7:"Lenoxin";i:5;s:7:"Lanicor";i:6;s:7:"Lanibos";i:7;s:9:"Lanadicor";i:8;s:11:"Halfdigoxin";i:9;s:8:"Fargoxin";i:10;s:7:"Eudigox";i:11;s:9:"Digoxinum";i:12;s:8:"Digoxine";i:13;s:7:"Digoxen";i:14;s:10:"Digoxanova";i:15;s:9:"Digossina";i:16;s:7:"Digosin";i:17;s:9:"Digoregen";i:18;s:7:"Digohan";i:19;s:10:"Digocard-g";i:20;s:7:"Digobal";i:21;s:7:"Digitek";i:22;s:8:"Digibind";i:23;s:9:"Digazolan";i:24;s:7:"Digacin";i:25;s:11:"Cardiogoxin";i:26;s:9:"Cardiacin";i:27;s:11:"Apo-digoxin";i:28;s:6:"Agoxin";}s:18:"active_ingredients";N;s:8:"packings";a:1:{s:4:"0.25";a:6:{i:4597;a:5:{s:10:"id_packing";s:4:"4597";s:5:"count";s:2:"60";s:6:"dosage";d:0.25;s:14:"price_per_pill";s:6:"0.6006";s:4:"name";s:7:"Lanoxin";}i:4598;a:5:{s:10:"id_packing";s:4:"4598";s:5:"count";s:2:"90";s:6:"dosage";d:0.25;s:14:"price_per_pill";s:7:"0.51892";s:4:"name";s:7:"Lanoxin";}i:4599;a:5:{s:10:"id_packing";s:4:"4599";s:5:"count";s:3:"120";s:6:"dosage";d:0.25;s:14:"price_per_pill";s:7:"0.47808";s:4:"name";s:7:"Lanoxin";}i:4600;a:5:{s:10:"id_packing";s:4:"4600";s:5:"count";s:3:"180";s:6:"dosage";d:0.25;s:14:"price_per_pill";s:7:"0.43724";s:4:"name";s:7:"Lanoxin";}i:4601;a:5:{s:10:"id_packing";s:4:"4601";s:5:"count";s:3:"270";s:6:"dosage";d:0.25;s:14:"price_per_pill";s:7:"0.41001";s:4:"name";s:7:"Lanoxin";}i:4602;a:5:{s:10:"id_packing";s:4:"4602";s:5:"count";s:3:"360";s:6:"dosage";d:0.25;s:14:"price_per_pill";s:6:"0.3964";s:4:"name";s:7:"Lanoxin";}}}}