a:18:{s:4:"name";s:9:"Meclizine";s:11:"small_descr";s:110:"Meclizine is used for preventing and treating nausea, vomiting, and dizziness associated with motion sickness.";s:14:"small_descr_de";s:119:"Meclizine dient der Vorbeugung und Behandlung von Übelkeit, Erbrechen und mit Bewegungskrankheit verbundene Schwindel.";s:14:"small_descr_fr";s:136:"Meclizine est utilisé pour prévenir et traiter les nausées, les vomissements et les étourdissements associés au mal des transports.";s:14:"small_descr_es";s:95:"Meclizine es usado para prevenir y tratar náuseas, vómitos y vértigos causados por el mareo.";s:14:"small_descr_it";s:89:"Meclizine si usa per il trattamento di nausea, vomito e capogiri causati dal mal di mare.";s:10:"full_descr";s:4675:"<p><strong>INDICATIONS</strong></p><p>Meclizine is used for preventing and treating nausea, vomiting, and dizziness associated with motion sickness. It is also used for vertigo (or dizziness) caused by certain inner ear problems. Meclizine is an anticholinergic. It works by blocking a chemical messenger in the brain, which helps to reduce or prevent vomiting.</p><p><strong>INSTRUCTIONS&nbsp;</strong></p><p>Use Meclizine as directed by your doctor.</p><ul><li>Take Meclizine by mouth with or without food.</li><li>For prevention of motion sickness, take Meclizine at least 1 hour before activity or travel.</li><li>Use Meclizine exactly as directed on the package, unless instructed differently by your doctor. If you are taking Meclizine without a prescription, follow any warnings and precautions on the label.</li><li>If you miss a dose of Meclizine and are using it regularly, take it as soon as possible. If it is almost time for your next dose, skip the missed dose and go back to your regular dosing schedule. Do not take 2 doses at once.</li></ul><p>Ask your health care provider any questions you may have about how to use Meclizine.</p><p><strong>STORAGE</strong></p><p>Store Meclizine at room temperature, between 59 and 86 degrees F (15 and 30 degrees C). Store away from heat, moisture, and light. Do not store in the bathroom. Keep Meclizine out of the reach of children and away from pets.<br /> <br /></p><p><strong>SAFETY INFORMATION</strong></p><p><strong>Do NOT use Meclizine if:</strong></p>
<ul>
<li>you are allergic to any ingredient in Meclizine</li>
<li>you are taking sodium oxybate (GHB).</li>
</ul>
<p>Contact your doctor or health care provider right away if any of these apply to you.</p>
<p>Some medical conditions may interact with Meclizine. Tell your doctor or pharmacist if you have any medical conditions, especially if any of the following apply to you:</p>
<ul>
<li>if you are pregnant, planning to become pregnant, or are breast-feeding</li>
<li>if you are taking any prescription or nonprescription medicine, herbal preparation, or dietary supplement</li>
<li>if you have allergies to medicines, foods, or other substances</li>
<li>you have asthma; chronic obstructive pulmonary disease (COPD); chronic bronchitis or emphysema; blockage of the stomach, intestine, or urinary tract;enlargement of the prostate; or glaucoma.</li>
</ul>
<p>Some medicines may interact with Meclizine. Tell your health care provider if you are taking any other medicines, especially any of the following:</p>
<ul>
<li>Sodium oxybate ( GHB) because an increase in sleep duration and a decrease in the ability to breathe are likely to occur.</li>
</ul>
<p>This may not be a complete list of all interactions that may occur. Ask your health care provider if Meclizine may interact with other medicines that you take. Check with your health care provider before you start, stop, or change the dose of any medicine.</p>
<p><strong>Important safety information:</strong></p>
<ul>
<li>Meclizine may cause drowsiness or blurred vision. This effect may be worse if you take it with alcohol or certain medicines. Use Meclizine with caution. Do not drive or perform other possible unsafe tasks until you know how you react to it.</li>
<li>Do not drink alcohol or use medicines that may cause drowsiness (eg, sleep aids, muscle relaxers) while you are using Meclizine; it may add to their effects. Ask your pharmacist if you have questions about which medicines may cause drowsiness.</li>
<li>Meclizine should not be used in children younger 12 years; safety and effectiveness in these children have not been confirmed.</li>
<li>Pregnancy and breast-feeding: If you become pregnant, contact your doctor. You will need to discuss the benefits and risks of using Meclizine while you are pregnant. It is not known if Meclizine is found in breast milk. If you are or will be breast-feeding while you use Meclizine, check with your doctor. Discuss any possible risks to your baby.</li>
</ul><p><strong>SIDE EFFECTS</strong></p><p>All medicines may cause side effects, but many people have no, or minor, side effects.</p>
<p>Check with your doctor if any of these most common side effects persist or become bothersome:</p>
<p>Drowsiness; dry mouth.</p>
<p>Seek medical attention right away if any of these severe side effects occur:</p>
<p>Severe allergic reactions (rash; hives; itching; difficulty breathing; tightness in the chest; swelling of the mouth, face, lips, or tongue).<br /> <br />&nbsp;This is not a complete list of all side effects that may occur. If you have questions about side effects, contact your health care provider.</p>";s:13:"full_descr_de";s:0:"";s:13:"full_descr_fr";s:0:"";s:13:"full_descr_es";s:0:"";s:13:"full_descr_it";s:0:"";s:9:"min_price";s:9:"0.4007157";s:9:"pack_name";s:5:"pills";s:4:"type";s:2:"mg";s:7:"analogs";a:1:{s:8:"Antivert";s:5:"Other";}s:8:"synonims";a:5:{i:0;s:6:"Meni-d";i:1;s:8:"Medivert";i:2;s:8:"Meclicot";i:3;s:12:"Driminate ii";i:4;s:6:"D-vert";}s:18:"active_ingredients";N;s:8:"packings";a:1:{i:25;a:6:{i:3564;a:5:{s:10:"id_packing";s:4:"3564";s:5:"count";s:2:"60";s:6:"dosage";d:25;s:14:"price_per_pill";s:7:"0.60715";s:4:"name";s:9:"Meclizine";}i:3565;a:5:{s:10:"id_packing";s:4:"3565";s:5:"count";s:2:"90";s:6:"dosage";d:25;s:14:"price_per_pill";s:7:"0.52457";s:4:"name";s:9:"Meclizine";}i:3566;a:5:{s:10:"id_packing";s:4:"3566";s:5:"count";s:3:"120";s:6:"dosage";d:25;s:14:"price_per_pill";s:7:"0.48329";s:4:"name";s:9:"Meclizine";}i:3567;a:5:{s:10:"id_packing";s:4:"3567";s:5:"count";s:3:"180";s:6:"dosage";d:25;s:14:"price_per_pill";s:5:"0.442";s:4:"name";s:9:"Meclizine";}i:3568;a:5:{s:10:"id_packing";s:4:"3568";s:5:"count";s:3:"270";s:6:"dosage";d:25;s:14:"price_per_pill";s:7:"0.41448";s:4:"name";s:9:"Meclizine";}i:3569;a:5:{s:10:"id_packing";s:4:"3569";s:5:"count";s:3:"360";s:6:"dosage";d:25;s:14:"price_per_pill";s:7:"0.40072";s:4:"name";s:9:"Meclizine";}}}}