a:18:{s:4:"name";s:10:"Amantadine";s:11:"small_descr";s:166:"Amantadine is used for preventing and treating certain types of flu. It is used to treat Parkinson disease and uncontrolled muscle movements caused by some medicines.";s:14:"small_descr_de";s:210:"Amantadine  wird zur Behandlung der durch Influenza-A-Viren verursachten Grippe und zur Behandlung des Parkinson-Syndroms  und durch eigene Arzneimittel verursachte unkontrollierte Muskelbewegungen  eingesetzt.";s:14:"small_descr_fr";s:209:"Amantadine est utilisé pour prévenir et traiter certaines formes de grippe. Il est utilisé pour traiter la maladie de Parkinson et des mouvements musculaires incontrôlés causée par certains médicaments.";s:14:"small_descr_es";s:217:"La amantadina es utilizada para prevenir y tratar ciertos tipos de gripe. Es utilizada para el tratamiento de la enfermedad de Parkinson y movimientos musculares incontrolables causados ​​por algunos medicamentos.";s:14:"small_descr_it";s:191:"Amantadine si usa per prevenire e trattare certi tipi dell'influenza. Si usa per il trattamento della malattia di Parkinson e movimenti muscolari incontrollabili causati da alcuni medicinali.";s:10:"full_descr";s:7551:"<p><strong>INDICATIONS</strong></p><p>Amantadine is used for preventing and treating certain types of flu. It is used to treat Parkinson disease and uncontrolled muscle movements caused by some medicines. Amantadine is an antiparkinson and antiviral agent. It may block reproduction of the virus and decrease the ability of the virus to get into the cells.</p><p><strong>INSTRUCTIONS&nbsp;</strong></p><p>Use Amantadine as directed by your doctor.</p><ul><li>Take Amantadine by mouth with or without food.</li><li>If you are using Amantadine for the flu, take it for the full course of treatment. Keep using Amantadine even if you feel better in a few days. This will help clear up your infection completely.</li><li>If you miss a dose of Amantadine, take it as soon as possible. If it is almost time for your next dose, skip the missed dose. Go back to your regular dosing schedule. Do not take 2 doses at once.</li></ul><p>Ask your health care provider any questions you may have about how to use Amantadine.</p><p><strong>STORAGE</strong></p><p>Store Amantadine at room temperature, between 59 and 86 degrees F (15 and 30 degrees C), in a tightly closed container. Store away from heat, moisture, and light. Do not store in the bathroom. Keep Amantadine out of the reach of children and away from pets.<br /> <br /></p><p><strong>SAFETY INFORMATION</strong></p><p><strong>Do NOT use Amantadine if:</strong></p>
<ul>
<li>you are allergic to any ingredient in Amantadine</li>
<li>you have uncontrolled narrow-angle glaucoma.</li>
</ul>
<p>Contact your doctor or health care provider right away if any of these apply to you.</p>
<p>Some medical conditions may interact with Amantadine. Tell your doctor or pharmacist if you have any medical conditions, especially if any of the following apply to you:</p>
<ul>
<li>if you are pregnant, planning to become pregnant, or are breast-feeding</li>
<li>if you are taking any prescription or nonprescription medicine, herbal preparation, or dietary supplement</li>
<li>if you have allergies to medicines, foods, or other substances</li>
<li>if you have a history of heart problems (eg, congestive heart failure), swelling of your hands or feet, mental or mood problems, suicidal thoughts or actions, seizures, glaucoma, low blood pressure, dizziness when you stand or sit up, an eczema-like rash, or kidney or liver problems</li>
<li>if you have received an intranasal flu vaccine within the last 14 days.</li>
</ul>
<p>Some medicines may interact with Amantadine. Tell your health care provider if you are taking any other medicines, especially any of the following:</p>
<ul>
<li>Thioridazine because tremors may be worsened in Parkinson patients</li>
<li>Anticholinergics (eg, scopolamine), hydrochlorothiazide, quinidine, quinine, stimulants (eg, caffeine, methylphenidate, pseudoephedrine), or triamterene because they may increase the risk of Amantadine's side effects.</li>
</ul>
<p>This may not be a complete list of all interactions that may occur. Ask your health care provider if Amantadine may interact with other medicines that you take. Check with your health care provider before you start, stop, or change the dose of any medicine.</p>
<p><strong>Important safety information:</strong></p>
<ul>
<li>Amantadine may cause drowsiness, dizziness, or blurred vision. These effects may be worse if you take it with alcohol or certain medicines. Use Amantadine with caution. Do not drive or perform other possible unsafe tasks until you know how you react to it.</li>
<li>Amantadine may cause dizziness, lightheadedness, or fainting; alcohol, hot weather, exercise, or fever may increase these effects. To prevent them, sit up or stand slowly, especially in the morning. Sit or lie down at the first sign of any of these effects.</li>
<li>Limit alcohol intake while you are taking Amantadine. Talk with you doctor before you drink alcohol or use medicines that may cause drowsiness (eg, sleep aids, muscle relaxers) while you are using Amantadine; it may add to their effects. Ask your pharmacist if you have questions about which medicines may cause drowsiness.</li>
<li>Do not become overheated in hot weather or while you are being active; heatstroke may occur.</li>
<li>Amantadine only works against certain types of the flu; it does not treat other viral infections (eg, the common cold).</li>
<li>If you are taking Amantadine for the flu, be sure to use Amantadine for the full course of treatment. If you do not, the medicine may not clear up your infection completely. The virus could also become less sensitive to this or other medicines. This could make the infection harder to treat in the future.</li>
<li>You usually should not receive a live nasal flu vaccine within 14 days before or 2 days after you take Amantadine. The vaccine may not work as well. Talk with your doctor before you receive any vaccine.</li>
<li>If you are taking Amantadine for Parkinson disease, increase physical activity slowly as your symptoms improve.</li>
<li>Do not suddenly stop taking Amantadine without first checking with your doctor. Your dose may need to be lowered slowly to avoid side effects.</li>
<li>Neuroleptic malignant syndrome (NMS) is a possibly fatal syndrome that can be caused by Amantadine. Symptoms may include fever; stiff muscles; confusion; abnormal thinking; fast or irregular heartbeat; and sweating. Contact your doctor at once if you have any of these symptoms.</li>
<li>If your symptoms do not get better or if they get worse, check with your doctor.</li>
<li>Use Amantadine with caution in the elderly; they may be more sensitive to its effects.</li>
<li>Amantadine should be used with extreme caution in children younger than 1 year old; safety and effectiveness in these children have not been confirmed.</li>
<li>Pregnancy and breast-feeding: If you become pregnant, contact your doctor. You will need to discuss the benefits and risks of using Amantadine while you are pregnant. Amantadine is found in breast milk. Do not breast-feed while taking Amantadine.</li>
</ul>
<p>If you stop taking Amantadine suddenly, you may have withdrawal symptoms. These may include agitation, hallucinations, paranoia, anxiety, depression, confusion, or slurred speech.</p><p><strong>SIDE EFFECTS</strong></p><p>All medicines may cause side effects, but many people have no, or minor, side effects.</p>
<p>Check with your doctor if any of these most common side effects persist or become bothersome:</p>
<p>Appetite loss; blurred vision; constipation; diarrhea; dizziness; drowsiness; dry mouth or nose; headache; lightheadedness; nausea; strange dreams; tiredness; trouble sleeping.<br /> <br /> Seek medical attention right away if any of these severe side effects occur:</p>
<p>Severe allergic reactions (rash; hives; itching; difficulty breathing; tightness in the chest; swelling of the mouth, face, lips, or tongue); aggression; agitation; confusion; depression; fainting; fast or irregular heartbeat; fever; hallucinations; memory loss; mental or mood changes; muscle problems (eg, spasms, uncontrolled movements); paranoid thoughts; personality changes; seizures; severe or persistent drowsiness or trouble sleeping; shortness of breath; sore throat; swelling of hands, legs, feet, or ankles; thoughts of suicide; trouble urinating; unusual anxiety or irritability; vision changes.<br /> <br />&nbsp;This is not a complete list of all side effects that may occur. If you have questions about side effects, contact your health care provider.</p>";s:13:"full_descr_de";s:0:"";s:13:"full_descr_fr";s:0:"";s:13:"full_descr_es";s:0:"";s:13:"full_descr_it";s:0:"";s:9:"min_price";s:8:"0.701784";s:9:"pack_name";s:5:"pills";s:4:"type";s:2:"mg";s:7:"analogs";N;s:8:"synonims";a:27:{i:0;s:8:"Virofral";i:1;s:7:"Viregyt";i:2;s:6:"Tregor";i:3;s:8:"Symadine";i:4;s:14:"Solu-contenton";i:5;s:8:"Protexin";i:6;s:8:"Paritrel";i:7;s:10:"Paramantin";i:8;s:8:"Mantadix";i:9;s:8:"Mantadan";i:10;s:7:"Lysovir";i:11;s:10:"Influenzol";i:12;s:11:"Endantadine";i:13;s:10:"Cerebramed";i:14;s:6:"Atarin";i:15;s:8:"Antadine";i:16;s:5:"Amixx";i:17;s:8:"Amentrel";i:18;s:8:"Amazolon";i:19;s:7:"Amantan";i:20;s:11:"Amantagamma";i:21;s:11:"Amantadinum";i:22;s:10:"Amantadina";i:23;s:10:"Amanta-hcl";i:24;s:4:"Aman";i:25;s:6:"Adekin";i:26;s:7:"Virosol";}s:18:"active_ingredients";N;s:8:"packings";a:1:{i:100;a:7:{i:3514;a:5:{s:10:"id_packing";s:4:"3514";s:5:"count";s:2:"30";s:6:"dosage";d:100;s:14:"price_per_pill";s:7:"1.16964";s:4:"name";s:10:"Amantadine";}i:3515;a:5:{s:10:"id_packing";s:4:"3515";s:5:"count";s:2:"60";s:6:"dosage";d:100;s:14:"price_per_pill";s:7:"0.91445";s:4:"name";s:10:"Amantadine";}i:3516;a:5:{s:10:"id_packing";s:4:"3516";s:5:"count";s:2:"90";s:6:"dosage";d:100;s:14:"price_per_pill";s:7:"0.82938";s:4:"name";s:10:"Amantadine";}i:3517;a:5:{s:10:"id_packing";s:4:"3517";s:5:"count";s:3:"120";s:6:"dosage";d:100;s:14:"price_per_pill";s:7:"0.78685";s:4:"name";s:10:"Amantadine";}i:3518;a:5:{s:10:"id_packing";s:4:"3518";s:5:"count";s:3:"180";s:6:"dosage";d:100;s:14:"price_per_pill";s:7:"0.74432";s:4:"name";s:10:"Amantadine";}i:3519;a:5:{s:10:"id_packing";s:4:"3519";s:5:"count";s:3:"270";s:6:"dosage";d:100;s:14:"price_per_pill";s:7:"0.71596";s:4:"name";s:10:"Amantadine";}i:3520;a:5:{s:10:"id_packing";s:4:"3520";s:5:"count";s:3:"360";s:6:"dosage";d:100;s:14:"price_per_pill";s:7:"0.70178";s:4:"name";s:10:"Amantadine";}}}}